name: walvagua_flutter
description: "Cliente Flutter multiplataforma de WallVagua"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  collection: ^1.19.1
  path: ^1.9.1
  share_plus: ^12.0.0
  cross_file: ^0.3.4+2
  flutter_wallpaper_manager: ^0.0.4
  app_settings: ^6.1.1
  flutter_animate: ^4.5.2
  flutter_glow: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_image.gif
    - assets/images/app_icon.webp
    - assets/images/app_icon_circle.webp

flutter_launcher_icons:
  image_path: assets/images/app_icon.png
  android: true
  ios: false
  windows:
    generate: true
    icon_size: 256
  fonts:
    - family: WallVagua
      fonts:
        - asset: assets/fonts/custom_font.ttf

